name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-12

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install -y visualstudio2019buildtools
          choco install -y visualstudio2019-workload-vctools

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --prefix install

      - name: Package with CPack
        run: cpack --config build/CPackConfig.cmake